### ISSUE TITLE
[REFACTOR] Development Guide

### ISSUE THREAD

**Issue by nugyn** [PGP1/rbpi-core#26]

**Comment by ijkeleher** [comment]
Try

```$ export AWS_ACCESS_KEY_ID=AKIAIOxxxxXAMPLE```
```$ export AWS_SECRET_ACCESS_KEY=wJalrXUtnFxxxxxMPLEKEY```
```$ export AWS_DEFAULT_REGION=ap-southeast-2```

And then you can run the bash script using these AWS_ACCESS_KEY_ID etc. variables

Alternatively you can use ENV in a Dockerfile @nugyn 

If you can't be bothered ping me and I'll set it up, do it at work all the time.

**Comment by nugyn** [comment]
Not sure why it was closed, haven't even finished the development guide.  I will do it, its not hard. Its better allocation of time if you complete your tasks. Thanks for the tip.
