### ISSUE TITLE
[US3.9] Ardiuno to RPI

### ISSUE THREAD

**Issue by nugyn** [PGP1/rbpi-core#4]

**Comment by ijkeleher** [comment]
https://gist.github.com/inci90/7829fec3fcc0eb487d6acb35889390e7

**Comment by nugyn** [comment]
Good work, I have added what has been done into the repo. I have modified the topic publish, and have setup the configuration of the pi itself to bridge between AWS IoT to a AWS Endpoint. Lambda functions can be subscribed to 2 topics, localgateway_to_awsiot and awsiot_to_localgateway, to denote traffic direction
